### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by lockieRichter** [shockbytes/DanteX#1]
Hi Martin,

I really love the app and have been wanting to rebuild it in Flutter for some time! I would love to get involved with this project, do you have a contribution guide and/or roadmap of features that you want developed so that I can help out?

Thanks,
Lockie

**Comment by shockbytes** [comment]
Hi @lockieRichter!

I finally manged to setup a contribution guide, updated the readme and created a backlog of features. You can see the open tickets here:
https://github.com/users/shockbytes/projects/1/views/1

And here's the link of the main communication channel on discord:
https://discord.com/channels/824694597728993390/1037365721363136572
