### ISSUE TITLE
Full login/signup functionality

### ISSUE THREAD

**Issue by shockbytes** [shockbytes/DanteX#4]
Implement Firebase Auth in the same way as supported on the old Dante Android App. Users should be able to login with Google, Email and anonymously. Furthermore, anonymous users should be able to upgrade to an email account later on.

One special requirement is to use the `Google Sign-In` dependency for Google signup, as these credentials are later on required to access the Google Drive backups

- [x] Login with Google 
- [x] Login anonymously 
- [x] Login with Email
- [x] Upgrade from anonymous user to email user

**Comment by lockieRichter** [comment]
@shockbytes This looks like a fun ticket that I'd like to take on.

If I might make a suggestion, it might be worth splitting this into 2 tickets instead.
1st Ticket
- Login with Google
- Login anonymously
- Login with Email
2nd Ticket
- Upgrade from anonymous user to email user
What do you think?

**Comment by shockbytes** [comment]
Absolutely, we can also split it further, as Email login is itself quite a topic.

In general, the app should support these methods (copied from the Android App)

```Kotlin
    fun loginWithGoogle(data: Intent): Completable

    fun fetchRegisteredAuthenticationSourcesForEmail(mailAddress: String): Single<List<AuthenticationSource>>

    fun createAccountWithMail(mailAddress: String, password: String): Completable

    fun loginWithMail(mailAddress: String, password: String): Completable

    fun updateMailPassword(password: String): Completable

    fun sendPasswordResetRequest(mailAddress: String): Completable

    fun loginAnonymously(): Completable

    fun logout(): Completable

    fun upgradeAnonymousAccount(mailAddress: String, password: String): Completable
```

**Comment by lockieRichter** [comment]
Yeah that's a good idea. Maybe we do a ticket for each form of login then?

**Comment by lockieRichter** [comment]
Also I've never used GitHub projects before, just getting my head around the workflow. I see that this issue has 4 tasks that we can sign off against, will have a go at the Login with Google task then.

**Comment by lockieRichter** [comment]
- Google sign in completed by pull PR #35 
- Anonymous sign in completed by PR #36

**Comment by shockbytes** [comment]
@lockieRichter do you think we should create a separate ticket for email login and the anonymous user upgrade?

**Comment by lockieRichter** [comment]
Yeah let's do that, I think each of those items should be a separate ticket. I am currently working on email login now, but it's going to be a bigger change so worth doing in its own ticket.

**Comment by shockbytes** [comment]
@lockieRichter I create a couple of subtasks / tickets for the complete login feature. Please find them referenced above.

**Comment by lockieRichter** [comment]
@shockbytes perfect, thank you!

**Comment by lockieRichter** [comment]
@shockbytes can you move this to done please.

**Comment by shockbytes** [comment]
@lockieRichter can we consider this issue as done?

**Comment by lockieRichter** [comment]
@shockbytes I think so, a user can login with google, email or anonymously, can reset their password and can upgrade from an anonymous account to email based.
