### ISSUE TITLE
Allow anonymous users to upgrade to an email account

### ISSUE THREAD

**Issue by shockbytes** [shockbytes/DanteX#43]
Anonymous customers should be able to enter an email address and a password to upgrade to an email account.

This ticket implements the following Android app method:

```Kotlin
    fun upgradeAnonymousAccount(mailAddress: String, password: String): Completable

```

**Comment by shockbytes** [comment]
Subtask of #4

**Comment by lockieRichter** [comment]
@shockbytes can you assign this one to me? And also update the permissions on the project so that I can edit/assign and transition tickets?

**Comment by shockbytes** [comment]
Let me check how I can do that because it seems like I can't change permissions right now.
